version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: agewell
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - swensen_volumn:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

volumes:
  swensen_volumn:
